#!/usr/bin/env python3
"""Synthetic, labelled QC-calibration fixtures for QC-CAL-01.

These seven FCS files are NOT real instrument acquisitions. Every event,
timestamp, and disturbance below is synthetically generated by this script
with the injected ground truth recorded in the sidecar manifest
(``qc_calibration/manifest.json``) -- never inferred, never embedded in the
FCS parameters themselves. They exist so the Time QC (``acquisition_time_qc.js``),
pulse-geometry singlet gate (``pulse_geometry_gate.js``), and scatter GMM cell
gate (``scatter_gmm_gate.js``) detectors can be exercised against a *known*,
controlled disturbance instead of only biological or parser-conformance truth.

This calibrates detection *behavior* against a known injected truth. It does
NOT and cannot substitute for QC-CAL-01's actual ask: real, independently
labelled acquisitions from an instrument operator or orthogonal source. Do not
represent these fixtures as real acquisitions in any report or discussion.

Like ``generate_fixtures.py``, this generator is deliberately independent of
PhaseFinder's production detector code -- it knows nothing about robust
z-scores, MAD thresholds, or ridge fitting. It only knows the physical/pulse
model used to synthesize events and the disturbances it deliberately injects.

Usage:
    python3 generate_qc_calibration_fixtures.py            # write fixtures + manifest
    python3 generate_qc_calibration_fixtures.py --check    # verify reproducibility
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from fcs_factory import Parameter, write_fcs  # noqa: E402

GENERATOR_NAME = "phasefinder-qc-calibration-synthetic"
GENERATOR_VERSION = "1.0.0"
SCHEMA_VERSION = 1
DEFAULT_OUTPUT = HERE / "qc_calibration"

PARAMETER_NAMES = ("DNA-A", "DNA-H", "DNA-W", "FSC-A", "SSC-A", "Time")

# Pulse/scatter model constants. Arbitrary but internally consistent units;
# nothing here is calibrated to a real instrument.
AREA_SCALE = 20_000.0
HEIGHT_SCALE = 9_000.0
BASE_WIDTH = 40.0
FSC_MEAN = 50_000.0
SSC_MEAN = 30_000.0

BASELINE_DOUBLET_FRACTION = 0.04
BASELINE_DEBRIS_FRACTION = 0.03
DOUBLET_HEAVY_FRACTION = 0.08
DEBRIS_DOMINANT_FRACTION = 0.60

EVENT_COUNT = 6_000
EVENT_RATE_HZ = 50.0
STABLE_TIME_RANGE = 100_000.0
ROLLOVER_TIME_RANGE = 40.0

DNA_A_RANGE = 262_144
DNA_H_RANGE = 131_072
DNA_W_RANGE = 1_024
FSC_A_RANGE = 262_144
SSC_A_RANGE = 262_144

CLOG_WINDOW = (2_400, 3_000)  # [start, end) event indexes, acquisition order
CLOG_RATE_STRETCH = 15.0
CLOG_FSC_MULTIPLIER = 1.18
CLOG_SSC_MULTIPLIER = 1.12
CLOG_DNA_A_MULTIPLIER = 1.05

DROPOUT_INDEX = 3_300  # gap inserted immediately before this event index
DROPOUT_GAP_SECONDS = 25.0

JUMP_INDEX = 2_700  # backward-time-jump segment boundary
JUMP_RESTART_OFFSET = 2.0


def _stream_rng(seed: int, stream: str) -> random.Random:
    """A named, SHA-256-derived, independent RNG stream (same technique as
    generate_fixtures.py) so each aspect of a fixture (biology, pulse noise,
    scatter noise, timing) can be perturbed without cross-contaminating another
    aspect's sequence, and the whole corpus is bit-reproducible from its seed."""
    digest = hashlib.sha256(f"{GENERATOR_VERSION}:{seed}:{stream}".encode()).digest()
    return random.Random(int.from_bytes(digest[:8], "big"))


def _truncated_normal(rng: random.Random, mean: float, sd: float, minimum: float = 1e-6) -> float:
    while True:
        value = rng.gauss(mean, sd)
        if value > minimum:
            return value


def _relative_dna_content(rng: random.Random) -> float:
    """G1 (60%) / S-bridge (25%) / G2 (15%) relative DNA content; G1=1.0, G2=2.0."""
    roll = rng.random()
    if roll < 0.60:
        return _truncated_normal(rng, 1.0, 0.04)
    if roll < 0.85:
        return rng.uniform(1.0, 2.0)
    return _truncated_normal(rng, 2.0, 0.06)


def _singlet_pulse(rng: random.Random, content: float) -> tuple[float, float, float]:
    area = content * AREA_SCALE * (1 + rng.gauss(0.0, 0.02))
    height = content * HEIGHT_SCALE * (1 + rng.gauss(0.0, 0.025))
    # A mild width/content correlation, as seen on real instruments, rather
    # than a content-independent nuisance value -- see the doublet-heavy
    # calibration note in _build_doublet_heavy() for why this matters.
    width = BASE_WIDTH * (1 + 0.1 * (content - 1.0)) * (1 + rng.gauss(0.0, 0.03))
    return max(area, 0.0), max(height, 0.0), max(width, 1.0)


def _doublet_pulse(rng: random.Random, content_a: float, content_b: float) -> tuple[float, float, float]:
    """Two coincident cells: Area sums (the detector integrates total
    fluorescence over the extended pulse) but Height does not double -- the
    electronics peak-detect one dominant crest, not a sum -- and Width widens.
    This is the physically-motivated Area/Height/Width divergence that a
    doublet-discrimination ridge gate is built to catch."""
    area = (content_a + content_b) * AREA_SCALE * (1 + rng.gauss(0.0, 0.02))
    height = max(content_a, content_b) * HEIGHT_SCALE * 0.55 * (1 + rng.gauss(0.0, 0.025))
    width = BASE_WIDTH * 1.8 * (1 + rng.gauss(0.0, 0.04))
    return max(area, 0.0), max(height, 0.0), max(width, 1.0)


def _live_scatter(rng: random.Random) -> tuple[float, float]:
    size_factor = _truncated_normal(rng, 1.0, 0.12, minimum=0.3)
    fsc = FSC_MEAN * size_factor * (1 + rng.gauss(0.0, 0.05))
    ssc = SSC_MEAN * size_factor * (1 + rng.gauss(0.0, 0.08))
    return max(fsc, 1.0), max(ssc, 1.0)


def _debris_scatter(rng: random.Random) -> tuple[float, float]:
    size_factor = _truncated_normal(rng, 0.22, 0.08, minimum=0.03)
    fsc = FSC_MEAN * size_factor * (1 + rng.gauss(0.0, 0.15))
    ssc = SSC_MEAN * size_factor * 0.6 * (1 + rng.gauss(0.0, 0.2))
    return max(fsc, 1.0), max(ssc, 1.0)


def _debris_pulse(rng: random.Random) -> tuple[float, float, float]:
    """Debris is not real cell-cycle content: a small, noisy, roughly
    exponential DNA-A signal (autofluorescence/fragments), not a G1/S/G2
    mixture, with an irregular (high relative jitter) pulse width."""
    content = rng.expovariate(1 / 0.18)
    width = BASE_WIDTH * (1 + rng.gauss(0.0, 0.25))
    area = content * AREA_SCALE * (1 + rng.gauss(0.0, 0.1))
    height = area / max(width, 1e-6) * BASE_WIDTH * 0.6
    return max(area, 0.0), max(height, 0.0), max(width, 1.0)


def _generate_population(
    seed: int,
    event_count: int,
    *,
    doublet_fraction: float,
    debris_fraction: float,
) -> list[dict]:
    """Generates biological/pulse identity per event, in acquisition order.
    Time is assigned separately by the caller so a scenario's Time disturbance
    can be layered on independently of which events are doublets/debris."""
    rng_debris = _stream_rng(seed, "debris-membership")
    rng_doublet = _stream_rng(seed, "doublet-membership")
    rng_dna = _stream_rng(seed, "dna-content")
    rng_pulse = _stream_rng(seed, "pulse-noise")
    rng_scatter = _stream_rng(seed, "scatter-noise")
    rng_debris_shape = _stream_rng(seed, "debris-shape")

    events = []
    for _ in range(event_count):
        is_debris = rng_debris.random() < debris_fraction
        if is_debris:
            area, height, width = _debris_pulse(rng_debris_shape)
            fsc, ssc = _debris_scatter(rng_scatter)
            events.append({
                "area": area, "height": height, "width": width,
                "fsc": fsc, "ssc": ssc,
                "is_debris": True, "is_doublet": False,
            })
            continue

        is_doublet = rng_doublet.random() < doublet_fraction
        if is_doublet:
            content_a = _relative_dna_content(rng_dna)
            content_b = _relative_dna_content(rng_dna)
            area, height, width = _doublet_pulse(rng_pulse, content_a, content_b)
        else:
            content = _relative_dna_content(rng_dna)
            area, height, width = _singlet_pulse(rng_pulse, content)
        fsc, ssc = _live_scatter(rng_scatter)
        events.append({
            "area": area, "height": height, "width": width,
            "fsc": fsc, "ssc": ssc,
            "is_debris": False, "is_doublet": is_doublet,
        })
    return events


def _baseline_time(seed: int, event_count: int, rate_hz: float, stretch_windows: list[tuple[int, int, float]]) -> list[float]:
    """Cumulative event times from exponential inter-arrival gaps at a constant
    baseline rate, with optional index-range gap stretches layered in (for the
    clog fixture)."""
    rng_time = _stream_rng(seed, "inter-arrival")
    mean_gap = 1.0 / rate_hz
    time = 0.0
    times = []
    for index in range(event_count):
        gap = rng_time.expovariate(1.0 / mean_gap) if index > 0 else 0.0
        for start, end, factor in stretch_windows:
            if start <= index < end:
                gap *= factor
                break
        time += gap
        times.append(time)
    return times


def _apply_dropout(times: list[float], dropout_index: int, gap_seconds: float) -> list[float]:
    shifted = list(times)
    for index in range(dropout_index, len(shifted)):
        shifted[index] += gap_seconds
    return shifted


def _apply_rollover(times: list[float], timer_range: float) -> tuple[list[float], list[int]]:
    wrapped = []
    wrap_indices = []
    previous_cycle = None
    for index, value in enumerate(times):
        cycle = int(value // timer_range)
        if previous_cycle is not None and cycle != previous_cycle:
            wrap_indices.append(index)
        previous_cycle = cycle
        wrapped.append(value - cycle * timer_range)
    return wrapped, wrap_indices


def _apply_backward_jump(times: list[float], jump_index: int, restart_offset: float) -> list[float]:
    shifted = list(times)
    pivot = shifted[jump_index]
    for index in range(jump_index, len(shifted)):
        shifted[index] = (shifted[index] - pivot) + restart_offset
    return shifted


def _apply_clog_channel_distortion(events: list[dict], window: tuple[int, int]) -> None:
    start, end = window
    for index in range(start, end):
        events[index]["fsc"] *= CLOG_FSC_MULTIPLIER
        events[index]["ssc"] *= CLOG_SSC_MULTIPLIER
        events[index]["area"] *= CLOG_DNA_A_MULTIPLIER


def _parameters(time_range: float) -> list[Parameter]:
    return [
        Parameter("DNA-A", stain="DNA-A", bits=32, range=DNA_A_RANGE),
        Parameter("DNA-H", stain="DNA-H", bits=32, range=DNA_H_RANGE),
        Parameter("DNA-W", stain="DNA-W", bits=32, range=DNA_W_RANGE),
        Parameter("FSC-A", stain="FSC-A", bits=32, range=FSC_A_RANGE),
        Parameter("SSC-A", stain="SSC-A", bits=32, range=SSC_A_RANGE),
        Parameter("Time", stain="Time", bits=32, range=time_range, unit="s"),
    ]


def _rows(events: list[dict], times: list[float]) -> list[list[float]]:
    return [
        [event["area"], event["height"], event["width"], event["fsc"], event["ssc"], time]
        for event, time in zip(events, times)
    ]


def _write_fixture(output: Path, name: str, events: list[dict], times: list[float], time_range: float) -> dict:
    rows = _rows(events, times)
    parameters = _parameters(time_range)
    path = output / f"{name}.fcs"
    build = write_fcs(path, rows, parameters)
    return {
        "path": f"{name}.fcs",
        "sha256": build.sha256,
        "event_count": len(rows),
    }


def _index_list(events: list[dict], key: str) -> list[int]:
    return [index for index, event in enumerate(events) if event[key]]


def _build_stable(seed: int) -> tuple[list[dict], list[float], float, dict]:
    events = _generate_population(
        seed, EVENT_COUNT,
        doublet_fraction=BASELINE_DOUBLET_FRACTION,
        debris_fraction=BASELINE_DEBRIS_FRACTION,
    )
    times = _baseline_time(seed, EVENT_COUNT, EVENT_RATE_HZ, [])
    truth = {
        "category": "stable",
        "target_qc_module": None,
        "injected_disturbance": None,
        "doublet_fraction": BASELINE_DOUBLET_FRACTION,
        "debris_fraction": BASELINE_DEBRIS_FRACTION,
        "doublet_event_indices": _index_list(events, "is_doublet"),
        "debris_event_indices": _index_list(events, "is_debris"),
        "expected_behavior": (
            "Negative control / false-positive-rate baseline for all three gates. "
            "Time QC should report a single segment with no flagged intervals; the "
            "pulse-geometry and scatter gates should retain nearly all events at "
            "only the small background doublet/debris rate above."
        ),
    }
    return events, times, STABLE_TIME_RANGE, truth


def _build_clog(seed: int) -> tuple[list[dict], list[float], float, dict]:
    events = _generate_population(
        seed, EVENT_COUNT,
        doublet_fraction=BASELINE_DOUBLET_FRACTION,
        debris_fraction=BASELINE_DEBRIS_FRACTION,
    )
    _apply_clog_channel_distortion(events, CLOG_WINDOW)
    times = _baseline_time(seed, EVENT_COUNT, EVENT_RATE_HZ, [(*CLOG_WINDOW, CLOG_RATE_STRETCH)])
    truth = {
        "category": "clog",
        "target_qc_module": "js/analysis/qc/acquisition_time_qc.js (runTimeQC)",
        "injected_disturbance": {
            "type": "localized event-rate slowdown with mild scatter/DNA-A distortion",
            "affected_event_index_range": list(CLOG_WINDOW),
            "rate_stretch_factor": CLOG_RATE_STRETCH,
            "fsc_multiplier": CLOG_FSC_MULTIPLIER,
            "ssc_multiplier": CLOG_SSC_MULTIPLIER,
            "dna_a_multiplier": CLOG_DNA_A_MULTIPLIER,
        },
        "doublet_fraction": BASELINE_DOUBLET_FRACTION,
        "debris_fraction": BASELINE_DEBRIS_FRACTION,
        "doublet_event_indices": _index_list(events, "is_doublet"),
        "debris_event_indices": _index_list(events, "is_debris"),
        "expected_behavior": (
            "runTimeQC should flag the bin(s) overlapping event indexes "
            f"{list(CLOG_WINDOW)} via the eventRate metric (and plausibly "
            "medianFSC_A/medianSSC_A/medianDNA_A too), producing at least one "
            "flaggedInterval overlapping this range."
        ),
    }
    return events, times, STABLE_TIME_RANGE, truth


def _build_dropout(seed: int) -> tuple[list[dict], list[float], float, dict]:
    events = _generate_population(
        seed, EVENT_COUNT,
        doublet_fraction=BASELINE_DOUBLET_FRACTION,
        debris_fraction=BASELINE_DEBRIS_FRACTION,
    )
    baseline = _baseline_time(seed, EVENT_COUNT, EVENT_RATE_HZ, [])
    times = _apply_dropout(baseline, DROPOUT_INDEX, DROPOUT_GAP_SECONDS)
    truth = {
        "category": "dropout",
        "target_qc_module": "js/analysis/qc/acquisition_time_qc.js (runTimeQC)",
        "injected_disturbance": {
            "type": "full acquisition gap (no events observed for a span of time)",
            "gap_inserted_before_event_index": DROPOUT_INDEX,
            "gap_seconds": DROPOUT_GAP_SECONDS,
        },
        "doublet_fraction": BASELINE_DOUBLET_FRACTION,
        "debris_fraction": BASELINE_DEBRIS_FRACTION,
        "doublet_event_indices": _index_list(events, "is_doublet"),
        "debris_event_indices": _index_list(events, "is_debris"),
        "expected_behavior": (
            f"The bin(s) spanning event index {DROPOUT_INDEX} should show a sharply "
            "elongated duration (hence depressed eventRate) relative to the robust "
            "baseline and be flagged; no channel-value distortion is injected here, "
            "only a timing gap."
        ),
    }
    return events, times, STABLE_TIME_RANGE, truth


def _build_timer_rollover(seed: int) -> tuple[list[dict], list[float], float, dict]:
    events = _generate_population(
        seed, EVENT_COUNT,
        doublet_fraction=BASELINE_DOUBLET_FRACTION,
        debris_fraction=BASELINE_DEBRIS_FRACTION,
    )
    baseline = _baseline_time(seed, EVENT_COUNT, EVENT_RATE_HZ, [])
    times, wrap_indices = _apply_rollover(baseline, ROLLOVER_TIME_RANGE)
    truth = {
        "category": "timer_rollover",
        "target_qc_module": "js/analysis/qc/acquisition_time_qc.js (prepareTimeQCBins)",
        "injected_disturbance": {
            "type": "deliberately small $PnR Time full-scale causing repeated wraps",
            "pnr_time": ROLLOVER_TIME_RANGE,
            "wrap_event_indices": wrap_indices,
        },
        "doublet_fraction": BASELINE_DOUBLET_FRACTION,
        "debris_fraction": BASELINE_DEBRIS_FRACTION,
        "doublet_event_indices": _index_list(events, "is_doublet"),
        "debris_event_indices": _index_list(events, "is_debris"),
        "expected_segment_count": 1,
        "expected_behavior": (
            "This is otherwise a well-behaved constant-rate acquisition -- the ONLY "
            "disturbance is the wraps themselves. prepareTimeQCBins should unwrap "
            "every wrap into a single continuous segment (segmentCount==1) and "
            "runTimeQC should NOT flag elevated bins from the wraps alone. This is a "
            "specificity / false-positive-rate check on the wrap-handling branch, "
            "not a positive-detection check."
        ),
    }
    return events, times, ROLLOVER_TIME_RANGE, truth


def _build_backward_time_jump(seed: int) -> tuple[list[dict], list[float], float, dict]:
    events = _generate_population(
        seed, EVENT_COUNT,
        doublet_fraction=BASELINE_DOUBLET_FRACTION,
        debris_fraction=BASELINE_DEBRIS_FRACTION,
    )
    baseline = _baseline_time(seed, EVENT_COUNT, EVENT_RATE_HZ, [])
    times = _apply_backward_jump(baseline, JUMP_INDEX, JUMP_RESTART_OFFSET)
    truth = {
        "category": "backward_time_jump",
        "target_qc_module": "js/analysis/qc/acquisition_time_qc.js (prepareTimeQCBins)",
        "injected_disturbance": {
            "type": "unrelated backward time jump (simulates a paused/restarted acquisition, not a timer wrap)",
            "jump_event_index": JUMP_INDEX,
            "restart_offset_seconds": JUMP_RESTART_OFFSET,
        },
        "doublet_fraction": BASELINE_DOUBLET_FRACTION,
        "debris_fraction": BASELINE_DEBRIS_FRACTION,
        "doublet_event_indices": _index_list(events, "is_doublet"),
        "debris_event_indices": _index_list(events, "is_debris"),
        "expected_segment_count": 2,
        "expected_behavior": (
            f"The backward move at event index {JUMP_INDEX} occurs far below "
            "80% of the (large) Time full-scale, so prepareTimeQCBins should classify "
            "it as an unrelated jump and start a new acquisition segment "
            "(segmentCount==2), and runTimeQC should report limitedReliability=true "
            "purely from segmentCount>1."
        ),
    }
    return events, times, STABLE_TIME_RANGE, truth


def _build_doublet_heavy(seed: int) -> tuple[list[dict], list[float], float, dict]:
    events = _generate_population(
        seed, EVENT_COUNT,
        doublet_fraction=DOUBLET_HEAVY_FRACTION,
        debris_fraction=BASELINE_DEBRIS_FRACTION,
    )
    times = _baseline_time(seed, EVENT_COUNT, EVENT_RATE_HZ, [])
    truth = {
        "category": "doublet_heavy",
        "target_qc_module": "js/analysis/gating/pulse_geometry_gate.js (gateByPulseGeometry)",
        "injected_disturbance": {
            "type": "elevated doublet fraction, uniformly distributed across acquisition time",
        },
        "doublet_fraction": DOUBLET_HEAVY_FRACTION,
        "debris_fraction": BASELINE_DEBRIS_FRACTION,
        "doublet_event_indices": _index_list(events, "is_doublet"),
        "debris_event_indices": _index_list(events, "is_debris"),
        "expected_behavior": (
            "gateByPulseGeometry should flag a majority of the doublet_event_indices "
            "events as off-ridge (excess Area relative to Height/at the widened "
            "Width). Time QC and the scatter gate should behave as in stable_run -- "
            "only the pulse-geometry gate is the intended target. CALIBRATION NOTE "
            "(found by running the real detector against this corpus): "
            "gateByPulseGeometry's robust ridge fit assumes doublets are a minority "
            "of the population (see its own module docstring). Sweeping this "
            "fixture's doublet fraction against the real gate shows recall holds "
            "near 1.0 up to roughly 8-10% doublets, then degrades progressively as "
            "the fraction rises further, and selectPulseGeometry's correlation-based "
            "DNA_H/DNA_W channel choice can itself flip to the weaker channel at "
            "conflated fractions. DOUBLET_HEAVY_FRACTION is deliberately set inside "
            "that still-reliable range so this fixture checks detection, not the "
            "breakdown point; the breakdown itself is a real, separate finding worth "
            "a scientific-result-contract note, not something this fixture asserts."
        ),
    }
    return events, times, STABLE_TIME_RANGE, truth


def _build_debris_dominant(seed: int) -> tuple[list[dict], list[float], float, dict]:
    events = _generate_population(
        seed, EVENT_COUNT,
        doublet_fraction=BASELINE_DOUBLET_FRACTION,
        debris_fraction=DEBRIS_DOMINANT_FRACTION,
    )
    times = _baseline_time(seed, EVENT_COUNT, EVENT_RATE_HZ, [])
    truth = {
        "category": "debris_dominant",
        "target_qc_module": "js/analysis/gating/scatter_gmm_gate.js (gateMainBiologicalCloud)",
        "injected_disturbance": {
            "type": "debris cluster outnumbers the live-cell cloud in FSC-A/SSC-A",
        },
        "doublet_fraction": BASELINE_DOUBLET_FRACTION,
        "debris_fraction": DEBRIS_DOMINANT_FRACTION,
        "doublet_event_indices": _index_list(events, "is_doublet"),
        "debris_event_indices": _index_list(events, "is_debris"),
        "expected_behavior": (
            "CALIBRATION FINDING (confirmed by running the real detector against "
            "this corpus, not assumed): gateMainBiologicalCloud selects its 'main' "
            f"component purely by population weight (see its selectionScore in "
            "scatter_gmm_gate.js). With debris at "
            f"{DEBRIS_DOMINANT_FRACTION:.0%} -- a genuine majority -- the debris "
            "cluster IS the higher-weight component, so the gate selects it as "
            "'main' and rejects the live-cell cloud instead: most non-debris events "
            "are incorrectly flagged (false-positive rate near 1.0) while most true "
            "debris events are retained (recall near 0). It also reports "
            "'review required' rather than a clean fit. This is the expected, "
            "correct behavior of the documented weight-based selection rule once "
            "debris crosses 50% of events -- it is a real operating-envelope limit "
            "of QC-05, not a bug in this fixture, and is worth a note in "
            "docs/scientific-result-contract.md: gateMainBiologicalCloud is only "
            "reliable while the live-cell population is the numeric majority."
        ),
    }
    return events, times, STABLE_TIME_RANGE, truth


FIXTURE_BUILDERS = {
    "stable_run": (1, _build_stable),
    "clog_run": (2, _build_clog),
    "dropout_run": (3, _build_dropout),
    "timer_rollover_run": (4, _build_timer_rollover),
    "backward_time_jump_run": (5, _build_backward_time_jump),
    "doublet_heavy_run": (6, _build_doublet_heavy),
    "debris_dominant_run": (7, _build_debris_dominant),
}


def _build_all(output: Path) -> Path:
    output.mkdir(parents=True, exist_ok=True)
    fixtures = {}
    for name, (seed, builder) in FIXTURE_BUILDERS.items():
        events, times, time_range, truth = builder(seed)
        file_info = _write_fixture(output, name, events, times, time_range)
        fixtures[name] = {**file_info, **truth}

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "generator": {
            "name": GENERATOR_NAME,
            "version": GENERATOR_VERSION,
            "command": "python3 tests/validation/validation_test_data/synthetic_fcs/generate_qc_calibration_fixtures.py",
            "randomness": "Named SHA-256-derived Python Random streams; committed artifacts are hash-pinned.",
        },
        "contains_real_data": False,
        "purpose": "QC-CAL-01 calibration fixtures: labelled acquisitions with a known, injected ground truth.",
        "disclaimer": (
            "This is SYNTHETIC data with injected known truth, not real "
            "flow-cytometer acquisition data. It must never be presented as, or "
            "substituted for, real independently-labelled acquisitions. It "
            "calibrates detector behavior against a controlled ground truth, "
            "which is a narrower claim than QC-CAL-01's actual ask."
        ),
        "shared_model": {
            "area_scale": AREA_SCALE,
            "height_scale": HEIGHT_SCALE,
            "base_width": BASE_WIDTH,
            "fsc_mean": FSC_MEAN,
            "ssc_mean": SSC_MEAN,
            "event_count": EVENT_COUNT,
            "event_rate_hz": EVENT_RATE_HZ,
            "baseline_doublet_fraction": BASELINE_DOUBLET_FRACTION,
            "baseline_debris_fraction": BASELINE_DEBRIS_FRACTION,
        },
        "channel_key_mapping": {
            "DNA-A": "DNA_A", "DNA-H": "DNA_H", "DNA-W": "DNA_W",
            "FSC-A": "FSC_A", "SSC-A": "SSC_A", "Time": "Time",
        },
        "fixtures": fixtures,
    }
    manifest_path = output / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest_path


def check(canonical: Path) -> int:
    with tempfile.TemporaryDirectory(prefix="phasefinder-qc-cal-check-") as temp_name:
        generated = Path(temp_name) / "qc_calibration"
        _build_all(generated)
        expected_files = sorted(path.name for path in generated.iterdir())
        canonical_files = sorted(path.name for path in canonical.iterdir()) if canonical.is_dir() else []
        if expected_files != canonical_files:
            print("Generated file list differs from the committed fixtures.", file=sys.stderr)
            print("expected:", *expected_files, sep="\n  ", file=sys.stderr)
            print("committed:", *canonical_files, sep="\n  ", file=sys.stderr)
            return 1
        mismatches = [
            name for name in expected_files
            if (generated / name).read_bytes() != (canonical / name).read_bytes()
        ]
        if mismatches:
            print("Regeneration mismatch:", *mismatches, sep="\n  ", file=sys.stderr)
            return 1
    print(f"QC-calibration fixtures are reproducible ({len(expected_files)} files checked).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Regenerate in a temporary directory and byte-compare.")
    args = parser.parse_args()
    output = args.output.resolve()
    if args.check:
        return check(output)
    manifest_path = _build_all(output)
    fixture_count = len(json.loads(manifest_path.read_text(encoding="utf-8"))["fixtures"])
    print(f"Generated {fixture_count} QC-calibration fixtures at {output}")
    print(f"Manifest: {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
