#!/usr/bin/env python3
"""Generate the JavaScript import inventory and reject new import cycles."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JS_ROOT = ROOT / "js"
OUTPUT = ROOT / "docs" / "module-import-graph.md"
ALLOWLIST = ROOT / "config" / "import-cycle-allowlist.json"
STATIC_IMPORT = re.compile(r"\b(?:import|export)\s+(?:[^;]*?\s+from\s+)?['\"]([^'\"]+)['\"]", re.MULTILINE)
DYNAMIC_IMPORT = re.compile(r"\bimport\(\s*['\"]([^'\"]+)['\"]\s*\)")
WORKER_URL = re.compile(r"\bnew\s+URL\(\s*['\"]([^'\"]+)['\"]\s*,\s*import\.meta\.url\s*\)")


def _resolve(source, reference):
    if not reference.startswith("."):
        return None
    target = (source.parent / reference).resolve()
    candidates = (target, target.with_suffix(".js"), target / "index.js") if not target.suffix else (target,)
    for candidate in candidates:
        if candidate.is_file() and candidate.suffix == ".js" and JS_ROOT in candidate.parents:
            return candidate.relative_to(ROOT).as_posix()
    return None


def graph():
    result = {}
    kinds = {}
    for path in sorted(JS_ROOT.rglob("*.js")):
        source = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8")
        edges = set()
        for kind, pattern in (("static", STATIC_IMPORT), ("dynamic", DYNAMIC_IMPORT), ("worker", WORKER_URL)):
            for reference in pattern.findall(text):
                target = _resolve(path, reference)
                if target:
                    edges.add(target)
                    kinds[(source, target)] = kind
        result[source] = sorted(edges)
    return result, kinds


def cyclic_components(imports):
    index = 0
    indexes, lowlinks, stack, on_stack, components = {}, {}, [], set(), []

    def visit(node):
        nonlocal index
        indexes[node] = lowlinks[node] = index
        index += 1
        stack.append(node)
        on_stack.add(node)
        for target in imports.get(node, ()):
            if target not in indexes:
                visit(target)
                lowlinks[node] = min(lowlinks[node], lowlinks[target])
            elif target in on_stack:
                lowlinks[node] = min(lowlinks[node], indexes[target])
        if lowlinks[node] == indexes[node]:
            component = []
            while True:
                target = stack.pop()
                on_stack.remove(target)
                component.append(target)
                if target == node:
                    break
            if len(component) > 1 or node in imports.get(node, ()):
                components.append(sorted(component))

    for node in imports:
        if node not in indexes:
            visit(node)
    return sorted(components)


def render(imports, kinds):
    lines = [
        "# JavaScript module import graph",
        "",
        "Generated by `python3 scripts/check_import_graph.py --update`. Do not edit by hand.",
        "Static imports, dynamic imports, and module-worker entry points are included; non-JavaScript assets are excluded.",
        "",
        f"Modules: {len(imports)}. Local edges: {sum(map(len, imports.values()))}.",
        "",
        "| Module | Local dependencies |",
        "| --- | --- |",
    ]
    for source, targets in imports.items():
        dependencies = ", ".join(
            f"`{target}`" + (f" ({kinds[(source, target)]})" if kinds[(source, target)] != "static" else "")
            for target in targets
        ) or "—"
        lines.append(f"| `{source}` | {dependencies} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="rewrite the generated Markdown after reviewing graph changes")
    parser.add_argument("--show-cycles", action="store_true")
    args = parser.parse_args()
    imports, kinds = graph()
    cycles = cyclic_components(imports)
    if args.show_cycles:
        print(json.dumps(cycles, indent=2))
        return 0
    allowed = json.loads(ALLOWLIST.read_text(encoding="utf-8"))
    if cycles != allowed:
        raise SystemExit("Import-cycle set changed; review it and update config/import-cycle-allowlist.json explicitly.\n" + json.dumps(cycles, indent=2))
    expected = render(imports, kinds)
    if args.update:
        OUTPUT.write_text(expected, encoding="utf-8")
    elif not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
        raise SystemExit("Module import graph is stale; run: python3 scripts/check_import_graph.py --update")
    print(f"Import graph passed: {len(imports)} modules, {sum(map(len, imports.values()))} edges, {len(cycles)} allowed cyclic components.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
